import type { Content } from '../types';

export const demo: Content['demo'] = {
  eyebrow: 'Worked example',
  title: 'One of the forty',
  lede: 'The draft is written from what the office already has on file.',
  noJs: 'Needs JavaScript. The message, draft and gate read the same either way.',
  fromLabel: 'From',
  subjectLabel: 'Subject',
  pickLead: 'Pick the desk nearest yours.',
  beatIn: 'What came in, 08:40',
  beatKnows: 'What your own files say',
  beatWrote: 'What it wrote back',
  beatNote: 'Switch one off and watch the draft lose it.',
  gateNote: 'There is no automatic send anywhere in this product. Someone reads it, changes what they want, and sends it themselves.',
  sendLabel: 'Send',
  editLabel: 'Edit',
  doneLabel: 'Done',
  sentStamp: 'Sent',
  draftStamp: 'Draft',
  sentChip: 'Sent by you, 08:41',
  dealLabel: 'Next letter',
  payoff: 'Nothing left this office until you pressed send. There is no other way out.',
  editNote: 'You changed it before it went out. That is what the first week looks like.',
  reLabel: 'Re',
  close: {
    before: 'You read it. You send it. ',
    mark: 'Nobody sat down and spent ',
    markEnd: ' minutes',
    after: ' writing it out.',
  },
  say: {
    allOff: 'Nothing left on. The draft is four generic lines.',
    restore: 'All five back on. The draft is whole again.',
    deal: 'A new letter on the desk. The draft is back to where it started.',
    sent: 'Sent. The draft left only because you pressed send.',
    edit: 'The draft is editable. Press Done, or Escape, when you have finished.',
    done: 'Editing finished. Your changes are kept.',
    source: 'Source: ',
    desk: ' desk. A different message, the same five sources.',
  },
  restoreLabel: 'Put it all back',
  allOffNote: 'This is what any other tool writes, with none of your files.',
  desks: [
    {
      id: 'property',
      tab: 'Property',
      deskName: 'Property',
      letter: {
        from: 'Hanne Jensen, flat 214',
        subject: 'Deposit statement, still nothing',
        body: 'I moved out on the 30th of last month and I still have not had the statement. The keys went back on time and the flat was clean. When am I getting my deposit and how much of it is left?',
      },
      sources: [
        {
          key: 'rules',
          label: 'the deposit rules',
          count: '1 line',
          name: 'the deposit rules',
          off: 'Deposit rules off. The draft stops naming the three week rule.',
          on: 'Deposit rules on. The three week rule is back in the draft.',
        },
        {
          key: 'deadline',
          label: 'the three week deadline',
          count: '1 line',
          name: 'the three week deadline',
          off: 'Deadline off. The date drops out of the draft.',
          on: 'Deadline on. The 21st is back in the draft.',
        },
        {
          key: 'file',
          label: 'the file on that flat',
          count: '2 lines',
          name: 'the file on that flat',
          off: 'File off. The tenant name and the account drop out of the draft.',
          on: 'File on. The tenant name and the account are back in the draft.',
        },
        {
          key: 'deductions',
          label: 'the deductions already logged',
          count: '3 figures',
          name: 'the deductions already logged',
          off: 'Deductions log off. Three figures removed from the draft.',
          on: 'Deductions log on. Three figures are back in the draft.',
        },
        {
          key: 'tone',
          label: 'the way the office writes',
          count: 'the tone',
          name: 'the way the office writes',
          off: 'House tone off. Same facts, stiffer wording.',
          on: 'House tone on. The draft reads in the office voice again.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Dear Ms Jensen,' },
          off: { text: 'Dear tenant,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Thank you for chasing this, and sorry you have had to.' },
          off: { text: 'Please be advised that your enquiry has been received.' },
        },
        {
          key: 'rules',
          on: { text: 'Your statement is due within three weeks of handover' },
          tone: { text: 'The statement is due within three weeks of handover' },
          off: { text: 'Your statement is due in line with the usual timescales' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'which puts it with you by ', circle: 'the 21st', tail: '.' },
          tone: { text: 'which places it with you by the 21st.' },
          off: { text: 'but I cannot give you the date without checking.' },
        },
        {
          key: 'deductions',
          on: { text: 'The two deductions raised so far are the end of tenancy clean at 850 EUR and the touch up to the hallway wall at 400 EUR. That leaves 4,750 EUR of your deposit to be paid back to' },
          tone: { text: 'Two deductions have been raised to date: the end of tenancy clean at 850 EUR and the touch up to the hallway wall at 400 EUR. The balance of 4,750 EUR is to be repaid to' },
          off: { text: 'There may be some deductions. I will confirm the amounts once I have checked.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'the account we hold.' },
          tone: { text: 'the account held on record.' },
          off: { text: 'your account.' },
        },
      ],
    },
    {
      id: 'accounting',
      tab: 'Accounting',
      deskName: 'Accounting',
      letter: {
        from: 'Mark Adeyemi, Harlow Joinery',
        subject: 'VAT return, are we late?',
        body: 'Our bookkeeper left in August and I have no idea where we stand. Has the return for the quarter gone in, and do we owe anything? I would rather hear it straight than get a letter about it.',
      },
      sources: [
        {
          key: 'rules',
          label: 'the filing rules',
          count: '1 line',
          name: 'the filing rules',
          off: 'Filing rules off. The draft stops naming the deadline rule.',
          on: 'Filing rules on. The one month and seven days rule is back in the draft.',
        },
        {
          key: 'deadline',
          label: 'the quarter deadline',
          count: '1 date',
          name: 'the quarter deadline',
          off: 'Deadline off. The date drops out of the draft.',
          on: 'Deadline on. The 7th is back in the draft.',
        },
        {
          key: 'file',
          label: 'the file on that client',
          count: '2 lines',
          name: 'the file on that client',
          off: 'File off. The client name and the direct debit drop out of the draft.',
          on: 'File on. The client name and the direct debit are back in the draft.',
        },
        {
          key: 'deductions',
          label: 'the figures already posted',
          count: '3 figures',
          name: 'the figures already posted',
          off: 'Posted figures off. Three figures removed from the draft.',
          on: 'Posted figures on. Three figures are back in the draft.',
        },
        {
          key: 'tone',
          label: 'the way the office writes',
          count: 'the tone',
          name: 'the way the office writes',
          off: 'House tone off. Same facts, stiffer wording.',
          on: 'House tone on. The draft reads in the office voice again.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Dear Mark,' },
          off: { text: 'Dear client,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Thank you for asking straight out, it is easier for both of us.' },
          off: { text: 'Please be advised that your enquiry has been received.' },
        },
        {
          key: 'rules',
          on: { text: 'Your return for the quarter to 31 July is due one calendar month and seven days after the quarter end' },
          tone: { text: 'The return for the quarter to 31 July is due one calendar month and seven days after the quarter end' },
          off: { text: 'Your return is due in line with the usual timescales' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'which puts your filing date at ', circle: 'the 7th', tail: '.' },
          tone: { text: 'which places the filing date at the 7th.' },
          off: { text: 'but I cannot give you the date without checking.' },
        },
        {
          key: 'deductions',
          on: { text: 'Everything is posted to the end of July: 41,280 EUR of sales VAT against 12,940 EUR reclaimed, which leaves 28,340 EUR to pay from' },
          tone: { text: 'All entries are posted to 31 July: sales VAT of 41,280 EUR against 12,940 EUR reclaimed, leaving 28,340 EUR payable from' },
          off: { text: 'There may be something to pay. I will confirm the amount once I have checked.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'the account we hold, by direct debit.' },
          tone: { text: 'the account held on record, by direct debit.' },
          off: { text: 'your account.' },
        },
      ],
    },
    {
      id: 'insurance',
      tab: 'Insurance',
      deskName: 'Insurance',
      letter: {
        from: 'Greta Poulsen, policy 4471-C',
        subject: 'Water damage, still no answer',
        body: 'The kitchen floor came up on the 2nd and your adjuster came out a week later. Nobody has told me what is covered. Am I paying the excess or are you, and when does any of it actually get paid?',
      },
      sources: [
        {
          key: 'rules',
          label: 'the policy wording',
          count: '1 section',
          name: 'the policy wording',
          off: 'Policy wording off. The draft stops naming the section and the excess.',
          on: 'Policy wording on. Section 4 and the excess are back in the draft.',
        },
        {
          key: 'deadline',
          label: 'the fourteen day standard',
          count: '1 date',
          name: 'the fourteen day standard',
          off: 'Deadline off. The date drops out of the draft.',
          on: 'Deadline on. The 18th is back in the draft.',
        },
        {
          key: 'file',
          label: 'the file on that claim',
          count: '2 lines',
          name: 'the file on that claim',
          off: 'File off. The claimant name and the account drop out of the draft.',
          on: 'File on. The claimant name and the account are back in the draft.',
        },
        {
          key: 'deductions',
          label: 'the amounts already agreed',
          count: '3 figures',
          name: 'the amounts already agreed',
          off: 'Agreed amounts off. Three figures removed from the draft.',
          on: 'Agreed amounts on. Three figures are back in the draft.',
        },
        {
          key: 'tone',
          label: 'the way the office writes',
          count: 'the tone',
          name: 'the way the office writes',
          off: 'House tone off. Same facts, stiffer wording.',
          on: 'House tone on. The draft reads in the office voice again.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Dear Ms Poulsen,' },
          off: { text: 'Dear policyholder,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Thank you for chasing this, and sorry you have had to.' },
          off: { text: 'Please be advised that your enquiry has been received.' },
        },
        {
          key: 'rules',
          on: { text: 'Escape of water is covered under section 4 of your policy, with the excess at 350 EUR' },
          tone: { text: 'Escape of water falls under section 4 of the policy, excess 350 EUR' },
          off: { text: 'Water damage is covered in the usual way' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'and we answer on cover within fourteen days of the adjuster’s report, which is ', circle: 'the 18th', tail: '.' },
          tone: { text: 'and cover is confirmed within fourteen days of the adjuster’s report, being the 18th.' },
          off: { text: 'but I cannot give you the date without checking.' },
        },
        {
          key: 'deductions',
          on: { text: 'The adjuster has agreed 6,200 EUR for the floor and 1,150 EUR for the drying, so after the excess 7,000 EUR goes to' },
          tone: { text: 'The adjuster has agreed 6,200 EUR for the floor and 1,150 EUR for drying; net of the excess, 7,000 EUR is payable to' },
          off: { text: 'There may be something to pay out. I will confirm the amounts once I have checked.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'the account we hold.' },
          tone: { text: 'the account held on record.' },
          off: { text: 'your account.' },
        },
      ],
    },
  ],
};
