import type { Content } from '../types';

export const form: Content['form'] = {
  eyebrow: 'What do I do now',
  title: 'Three questions. Under a minute.',
  lead: 'This is how we work out whether a call is worth your time. If it is not, this page will say so instead of booking you in.',
  formNo: 'Fit check',
  optional: 'Optional',
  companyLabel: 'Company name',
  companyPlaceholder: 'The name on your invoices',
  emailLabel: 'Work email',
  emailPlaceholder: 'you@yourfirm.com',
  emailHint: 'Only used to send the call details and the pilot agreement.',
  emailFreeWarning:
    'That looks like a personal address. It will still work, but a work address helps us find your firm before we speak.',
  phoneLabel: 'Phone',
  phoneHint: 'So we can reach you if the email bounces. Used for this call and nothing else.',
  teamSizeLabel: 'How many people handle email daily?',
  teamSizeOptions: [
    { value: '1-9', label: '1 to 9 people' },
    { value: '10-24', label: '10 to 24 people' },
    { value: '25-49', label: '25 to 49 people' },
    { value: '50+', label: '50 or more' },
  ],
  emailClientLabel: 'What does the team use?',
  emailClientOptions: [
    { value: 'outlook', label: 'Outlook' },
    { value: 'gmail', label: 'Gmail' },
    { value: 'other', label: 'Something else' },
  ],
  roleLabel: 'Your role',
  roleOptions: [
    { value: 'owner_partner', label: 'Owner or partner' },
    { value: 'ops_office_manager', label: 'Operations or office manager' },
    { value: 'it_admin', label: 'IT or admin' },
    { value: 'other', label: 'Something else' },
  ],
  otherLabel: 'Tell us which',
  choosePrompt: 'Choose one',
  steps: ['About the team', 'How to reach you'],
  stepsLabel: 'The fit check, in two steps',
  continueCta: 'Continue',
  backCta: 'Back',
  submit: 'Check if we are a fit',
  submitting: 'One moment',
  required: 'This one is needed.',
  invalidEmail: 'That address does not look complete.',
  invalidPhone: 'That does not look like enough digits for a number.',
  privacyNote: 'Used to prepare for the call. No list, no resale.',
};
