import type { Content } from '../types';

export const demo: Content['demo'] = {
  eyebrow: 'Gennemgået eksempel',
  title: 'En af de fyrre',
  lede: 'Udkastet er skrevet ud fra det, kontoret allerede har på sagen.',
  noJs: 'Kræver JavaScript. Mailen, udkastet og spærren siger det samme uanset hvad.',
  fromLabel: 'Fra',
  subjectLabel: 'Emne',
  pickLead: 'Vælg det skrivebord, der ligner jeres mest.',
  beatIn: 'Det, der kom ind, 08:40',
  beatKnows: 'Det, jeres egne sager siger',
  beatWrote: 'Det, den skrev tilbage',
  beatNote: 'Slå en fra, og se udkastet miste den.',
  gateNote: 'Der er ingen automatisk afsendelse nogen steder i produktet. Et menneske læser det, retter det, det vil, og sender selv.',
  sendLabel: 'Send',
  editLabel: 'Ret',
  doneLabel: 'Færdig',
  sentStamp: 'Sendt',
  draftStamp: 'Udkast',
  sentChip: 'Sendt af dig, 08:41',
  dealLabel: 'Næste brev',
  payoff: 'Intet forlod kontoret, før du trykkede send. Der er ingen anden vej ud.',
  editNote: 'Du rettede det, før det blev sendt. Sådan ser den første uge ud.',
  reLabel: 'Vedr',
  close: {
    before: 'Du læser det. Du sender det. ',
    mark: 'Ingen satte sig ned og brugte ',
    markEnd: ' minutter',
    after: ' på at skrive det.',
  },
  say: {
    allOff: 'Intet er slået til. Udkastet er fire intetsigende linjer.',
    restore: 'Alle fem er slået til igen. Udkastet er helt.',
    deal: 'Et nyt brev på bordet. Udkastet er tilbage, hvor det startede.',
    sent: 'Sendt. Udkastet forlod kun kontoret, fordi du trykkede send.',
    edit: 'Udkastet kan rettes. Tryk Færdig, eller Escape, når du er klar.',
    done: 'Rettelsen er afsluttet. Dine ændringer er beholdt.',
    source: 'Kilde: ',
    desk: '-skrivebordet. En anden mail, de samme fem kilder.',
  },
  restoreLabel: 'Sæt det hele tilbage',
  allOffNote: 'Sådan skriver ethvert andet værktøj, uden jeres sager.',
  desks: [
    {
      id: 'property',
      tab: 'Ejendom',
      deskName: 'Ejendoms',
      letter: {
        from: 'Hanne Jensen, lejlighed 214',
        subject: 'Fraflytningsopgørelse, stadig intet',
        body: 'Jeg flyttede ud den 30. i sidste måned, og jeg har stadig ikke fået opgørelsen. Nøglerne blev afleveret til tiden, og lejligheden var rengjort. Hvornår får jeg mit depositum, og hvor meget er der tilbage af det?',
      },
      sources: [
        {
          key: 'rules',
          label: 'reglerne om depositum',
          count: '1 linje',
          name: 'reglerne om depositum',
          off: 'Depositumreglerne er slået fra. Udkastet nævner ikke længere fristen på tre uger.',
          on: 'Depositumreglerne er slået til. Fristen på tre uger er tilbage i udkastet.',
        },
        {
          key: 'deadline',
          label: 'fristen på tre uger',
          count: '1 dato',
          name: 'fristen på tre uger',
          off: 'Fristen er slået fra. Datoen forsvinder ud af udkastet.',
          on: 'Fristen er slået til. Den 21. er tilbage i udkastet.',
        },
        {
          key: 'file',
          label: 'sagen på den lejlighed',
          count: '2 linjer',
          name: 'sagen på den lejlighed',
          off: 'Sagen er slået fra. Lejerens navn og kontoen forsvinder ud af udkastet.',
          on: 'Sagen er slået til. Lejerens navn og kontoen er tilbage i udkastet.',
        },
        {
          key: 'deductions',
          label: 'de fradrag, der allerede er noteret',
          count: '3 beløb',
          name: 'de fradrag, der allerede er noteret',
          off: 'Fradragslisten er slået fra. Tre beløb er fjernet fra udkastet.',
          on: 'Fradragslisten er slået til. Tre beløb er tilbage i udkastet.',
        },
        {
          key: 'tone',
          label: 'den måde kontoret skriver på',
          count: 'tonen',
          name: 'den måde kontoret skriver på',
          off: 'Kontortonen er slået fra. Samme fakta, stivere sprog.',
          on: 'Kontortonen er slået til. Udkastet lyder som kontoret igen.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Kære Hanne Jensen,' },
          off: { text: 'Kære lejer,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Tak fordi du rykker, og undskyld at det har været nødvendigt.' },
          off: { text: 'Det bekræftes hermed, at din henvendelse er modtaget.' },
        },
        {
          key: 'rules',
          on: { text: 'Opgørelsen skal være hos dig senest tre uger efter afleveringen' },
          tone: { text: 'Opgørelsen skal fremsendes senest tre uger efter afleveringen' },
          off: { text: 'Opgørelsen sendes inden for de sædvanlige frister' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'hvilket vil sige senest ', circle: 'den 21', tail: '.' },
          tone: { text: 'hvilket vil sige senest den 21.' },
          off: { text: 'men jeg kan ikke oplyse datoen uden at undersøge det.' },
        },
        {
          key: 'deductions',
          on: { text: 'De to fradrag, der er rejst indtil nu, er flytterengøring på 850 EUR og pletmaling af væggen i entreen på 400 EUR. Der resterer dermed 4.750 EUR af dit depositum, som betales tilbage til' },
          tone: { text: 'Der er hidtil rejst to fradrag: flytterengøring på 850 EUR og pletmaling af væggen i entreen på 400 EUR. Restbeløbet på 4.750 EUR tilbagebetales til' },
          off: { text: 'Der kan komme nogle fradrag. Jeg bekræfter beløbene, når jeg har undersøgt det.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'den konto, vi har registreret.' },
          tone: { text: 'den registrerede konto.' },
          off: { text: 'din konto.' },
        },
      ],
    },
    {
      id: 'accounting',
      tab: 'Revision',
      deskName: 'Revisions',
      letter: {
        from: 'Mads Kjær, Kjær Snedkeri',
        subject: 'Momsangivelsen, er vi bagud?',
        body: 'Vores bogholder stoppede i august, og jeg aner ikke, hvor vi står. Er angivelsen for kvartalet sendt ind, og skylder vi noget? Jeg vil hellere høre det lige ud end få et brev om det.',
      },
      sources: [
        {
          key: 'rules',
          label: 'reglerne for indberetning',
          count: '1 linje',
          name: 'reglerne for indberetning',
          off: 'Indberetningsreglerne er slået fra. Udkastet nævner ikke længere fristreglen.',
          on: 'Indberetningsreglerne er slået til. Reglen om en måned og syv dage er tilbage i udkastet.',
        },
        {
          key: 'deadline',
          label: 'kvartalets frist',
          count: '1 dato',
          name: 'kvartalets frist',
          off: 'Fristen er slået fra. Datoen forsvinder ud af udkastet.',
          on: 'Fristen er slået til. Den 7. er tilbage i udkastet.',
        },
        {
          key: 'file',
          label: 'sagen på den kunde',
          count: '2 linjer',
          name: 'sagen på den kunde',
          off: 'Sagen er slået fra. Kundens navn og betalingsservice forsvinder ud af udkastet.',
          on: 'Sagen er slået til. Kundens navn og betalingsservice er tilbage i udkastet.',
        },
        {
          key: 'deductions',
          label: 'de tal, der allerede er bogført',
          count: '3 beløb',
          name: 'de tal, der allerede er bogført',
          off: 'De bogførte tal er slået fra. Tre beløb er fjernet fra udkastet.',
          on: 'De bogførte tal er slået til. Tre beløb er tilbage i udkastet.',
        },
        {
          key: 'tone',
          label: 'den måde kontoret skriver på',
          count: 'tonen',
          name: 'den måde kontoret skriver på',
          off: 'Kontortonen er slået fra. Samme fakta, stivere sprog.',
          on: 'Kontortonen er slået til. Udkastet lyder som kontoret igen.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Kære Mads,' },
          off: { text: 'Kære kunde,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Tak fordi du spørger lige ud, det er nemmest for os begge.' },
          off: { text: 'Det bekræftes hermed, at din henvendelse er modtaget.' },
        },
        {
          key: 'rules',
          on: { text: 'Angivelsen for kvartalet til den 31. juli skal være inde en måned og syv dage efter kvartalets udløb' },
          tone: { text: 'Angivelsen for kvartalet til den 31. juli skal indsendes en måned og syv dage efter kvartalets udløb' },
          off: { text: 'Angivelsen skal indsendes inden for de sædvanlige frister' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'hvilket giver jer frist ', circle: 'den 7', tail: '.' },
          tone: { text: 'hvilket giver fristen den 7.' },
          off: { text: 'men jeg kan ikke oplyse datoen uden at undersøge det.' },
        },
        {
          key: 'deductions',
          on: { text: 'Alt er bogført til og med juli: 41.280 EUR i salgsmoms mod 12.940 EUR i fradrag, så der skal betales 28.340 EUR fra' },
          tone: { text: 'Samtlige posteringer er bogført til den 31. juli: salgsmoms på 41.280 EUR mod 12.940 EUR i fradrag, hvilket giver 28.340 EUR til betaling fra' },
          off: { text: 'Der kan være noget at betale. Jeg bekræfter beløbet, når jeg har undersøgt det.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'den konto, vi har registreret, via betalingsservice.' },
          tone: { text: 'den registrerede konto, via betalingsservice.' },
          off: { text: 'din konto.' },
        },
      ],
    },
    {
      id: 'insurance',
      tab: 'Forsikring',
      deskName: 'Forsikrings',
      letter: {
        from: 'Grethe Poulsen, police 4471-C',
        subject: 'Vandskade, stadig intet svar',
        body: 'Køkkengulvet bulede op den 2., og jeres taksator kom ud en uge senere. Ingen har fortalt mig, hvad der er dækket. Skal jeg betale selvrisikoen, eller skal I, og hvornår bliver noget af det egentlig udbetalt?',
      },
      sources: [
        {
          key: 'rules',
          label: 'policens ordlyd',
          count: '1 afsnit',
          name: 'policens ordlyd',
          off: 'Policens ordlyd er slået fra. Udkastet nævner ikke længere afsnittet og selvrisikoen.',
          on: 'Policens ordlyd er slået til. Afsnit 4 og selvrisikoen er tilbage i udkastet.',
        },
        {
          key: 'deadline',
          label: 'fristen på fjorten dage',
          count: '1 dato',
          name: 'fristen på fjorten dage',
          off: 'Fristen er slået fra. Datoen forsvinder ud af udkastet.',
          on: 'Fristen er slået til. Den 18. er tilbage i udkastet.',
        },
        {
          key: 'file',
          label: 'sagen på den skade',
          count: '2 linjer',
          name: 'sagen på den skade',
          off: 'Sagen er slået fra. Skadelidtes navn og kontoen forsvinder ud af udkastet.',
          on: 'Sagen er slået til. Skadelidtes navn og kontoen er tilbage i udkastet.',
        },
        {
          key: 'deductions',
          label: 'de beløb, der allerede er godkendt',
          count: '3 beløb',
          name: 'de beløb, der allerede er godkendt',
          off: 'De godkendte beløb er slået fra. Tre beløb er fjernet fra udkastet.',
          on: 'De godkendte beløb er slået til. Tre beløb er tilbage i udkastet.',
        },
        {
          key: 'tone',
          label: 'den måde kontoret skriver på',
          count: 'tonen',
          name: 'den måde kontoret skriver på',
          off: 'Kontortonen er slået fra. Samme fakta, stivere sprog.',
          on: 'Kontortonen er slået til. Udkastet lyder som kontoret igen.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Kære Grethe Poulsen,' },
          off: { text: 'Kære forsikringstager,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Tak fordi du rykker, og undskyld at det har været nødvendigt.' },
          off: { text: 'Det bekræftes hermed, at din henvendelse er modtaget.' },
        },
        {
          key: 'rules',
          on: { text: 'Vandskade er dækket efter policens afsnit 4, med en selvrisiko på 350 EUR' },
          tone: { text: 'Vandskade henhører under policens afsnit 4, selvrisiko 350 EUR' },
          off: { text: 'Vandskade er dækket på sædvanlig vis' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'og vi melder tilbage om dækningen senest fjorten dage efter taksatorrapporten, altså ', circle: 'den 18', tail: '.' },
          tone: { text: 'og dækningen bekræftes senest fjorten dage efter taksatorrapporten, altså den 18.' },
          off: { text: 'men jeg kan ikke oplyse datoen uden at undersøge det.' },
        },
        {
          key: 'deductions',
          on: { text: 'Taksator har godkendt 6.200 EUR til gulvet og 1.150 EUR til affugtning, så efter selvrisiko udbetales 7.000 EUR til' },
          tone: { text: 'Taksator har godkendt 6.200 EUR til gulvet og 1.150 EUR til affugtning; efter selvrisiko udgør beløbet 7.000 EUR, som udbetales til' },
          off: { text: 'Der kan komme en udbetaling. Jeg bekræfter beløbene, når jeg har undersøgt det.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'den konto, vi har registreret.' },
          tone: { text: 'den registrerede konto.' },
          off: { text: 'din konto.' },
        },
      ],
    },
  ],
};
