import type { Content } from '../types';

export const form: Content['form'] = {
  eyebrow: 'Hvad gør jeg nu',
  title: 'Tre spørgsmål. Under et minut.',
  lead: 'Sådan finder vi ud af, om et møde er din tid værd. Er det ikke det, siger den her side det i stedet for at booke dig.',
  formNo: 'Pasformstjek',
  optional: 'Valgfrit',
  companyLabel: 'Virksomhedens navn',
  companyPlaceholder: 'Navnet på jeres fakturaer',
  emailLabel: 'Arbejdsmail',
  emailPlaceholder: 'dig@ditfirma.dk',
  emailHint: 'Bruges kun til at sende mødedetaljer og pilotaftalen.',
  phoneLabel: 'Telefon',
  phoneHint: 'Så vi kan få fat i jer, hvis mailen ikke når frem. Bruges til dette møde og intet andet.',
  emailFreeWarning:
    'Det ligner en privat adresse. Den virker fint, men en arbejdsmail hjælper os med at finde jeres virksomhed, inden vi taler sammen.',
  teamSizeLabel: 'Hvor mange sidder med mails hver dag?',
  teamSizeOptions: [
    { value: '1-9', label: '1 til 9 personer' },
    { value: '10-24', label: '10 til 24 personer' },
    { value: '25-49', label: '25 til 49 personer' },
    { value: '50+', label: '50 eller flere' },
  ],
  emailClientLabel: 'Hvad bruger teamet?',
  emailClientOptions: [
    { value: 'outlook', label: 'Outlook' },
    { value: 'gmail', label: 'Gmail' },
    { value: 'other', label: 'Noget andet' },
  ],
  roleLabel: 'Din rolle',
  roleOptions: [
    { value: 'owner_partner', label: 'Ejer eller partner' },
    { value: 'ops_office_manager', label: 'Drift eller kontorchef' },
    { value: 'it_admin', label: 'IT eller administration' },
    { value: 'other', label: 'Noget andet' },
  ],
  otherLabel: 'Fortæl os hvilken',
  choosePrompt: 'Vælg en',
  steps: ['Om teamet', 'Sådan får vi fat i jer'],
  stepsLabel: 'Tjekket, i to trin',
  continueCta: 'Videre',
  backCta: 'Tilbage',
  submit: 'Se om vi passer sammen',
  submitting: 'Et øjeblik',
  required: 'Den her skal udfyldes.',
  invalidEmail: 'Den adresse ser ikke komplet ud.',
  invalidPhone: 'Det ser ikke ud til at være cifre nok til et nummer.',
  privacyNote: 'Bruges til at forberede mødet. Ingen liste, intet videresalg.',
};
