import type { Content } from '../types';

export const demo: Content['demo'] = {
  eyebrow: 'Išnagrinėtas pavyzdys',
  title: 'Vienas iš keturiasdešimties',
  lede: 'Juodraštis parašytas iš to, ką biuras jau turi byloje.',
  noJs: 'Reikia JavaScript. Laiškas, juodraštis ir stabdys sako tą patį bet kuriuo atveju.',
  fromLabel: 'Nuo',
  subjectLabel: 'Tema',
  pickLead: 'Pasirinkite stalą, artimiausią Jūsiškiam.',
  beatIn: 'Kas atėjo, 08:40',
  beatKnows: 'Ką sako Jūsų pačių bylos',
  beatWrote: 'Ką jis parašė atgal',
  beatNote: 'Išjunkite vieną ir žiūrėkite, kaip juodraštis jos netenka.',
  gateNote: 'Šiame produkte niekur nėra automatinio išsiuntimo. Žmogus perskaito, pakeičia, ką nori, ir išsiunčia pats.',
  sendLabel: 'Siųsti',
  editLabel: 'Taisyti',
  doneLabel: 'Baigta',
  sentStamp: 'Išsiųsta',
  draftStamp: 'Juodraštis',
  sentChip: 'Išsiuntėte Jūs, 08:41',
  dealLabel: 'Kitas laiškas',
  payoff: 'Iš šio biuro niekas neišėjo, kol nepaspaudėte siųsti. Kito kelio laukan nėra.',
  editNote: 'Jūs jį pakeitėte prieš išsiunčiant. Būtent taip atrodo pirma savaitė.',
  reLabel: 'Dėl',
  close: {
    before: 'Jūs perskaitote. Jūs išsiunčiate. ',
    mark: 'Niekas nepraleido ',
    markEnd: ' minučių',
    after: ' jį rašydamas.',
  },
  say: {
    allOff: 'Nieko neliko įjungta. Juodraštis yra keturios bendro pobūdžio eilutės.',
    restore: 'Visi penki vėl įjungti. Juodraštis vėl pilnas.',
    deal: 'Ant stalo naujas laiškas. Juodraštis grįžo į pradžią.',
    sent: 'Išsiųsta. Juodraštis išėjo tik todėl, kad paspaudėte siųsti.',
    edit: 'Juodraštį galima taisyti. Baigę spauskite Baigta arba Escape.',
    done: 'Taisymas baigtas. Jūsų pakeitimai išsaugoti.',
    source: 'Šaltinis: ',
    desk: ' stalas. Kitas laiškas, tie patys penki šaltiniai.',
  },
  restoreLabel: 'Grąžinti viską',
  allOffNote: 'Taip rašo bet kuris kitas įrankis, neturėdamas Jūsų bylų.',
  desks: [
    {
      id: 'property',
      tab: 'Nekilnojamasis turtas',
      deskName: 'Nekilnojamojo turto',
      letter: {
        from: 'Rasa Jankauskienė, butas 214',
        subject: 'Atsiskaitymas už užstatą, vis dar nieko',
        body: 'Išsikrausčiau praėjusio mėnesio 30 dieną ir vis dar negavau atsiskaitymo. Raktus grąžinau laiku, butas buvo švarus. Kada atgausiu užstatą ir kiek jo liko?',
      },
      sources: [
        {
          key: 'rules',
          label: 'užstato taisyklės',
          count: '1 eilutė',
          name: 'užstato taisyklės',
          off: 'Užstato taisyklės išjungtos. Juodraštis nebemini trijų savaičių taisyklės.',
          on: 'Užstato taisyklės įjungtos. Trijų savaičių taisyklė vėl juodraštyje.',
        },
        {
          key: 'deadline',
          label: 'trijų savaičių terminas',
          count: '1 data',
          name: 'trijų savaičių terminas',
          off: 'Terminas išjungtas. Data dingsta iš juodraščio.',
          on: 'Terminas įjungtas. 21 diena vėl juodraštyje.',
        },
        {
          key: 'file',
          label: 'to buto byla',
          count: '2 eilutės',
          name: 'to buto byla',
          off: 'Byla išjungta. Nuomininkės vardas ir sąskaita dingsta iš juodraščio.',
          on: 'Byla įjungta. Nuomininkės vardas ir sąskaita vėl juodraštyje.',
        },
        {
          key: 'deductions',
          label: 'jau užfiksuoti atskaitymai',
          count: '3 sumos',
          name: 'jau užfiksuoti atskaitymai',
          off: 'Atskaitymų sąrašas išjungtas. Trys sumos pašalintos iš juodraščio.',
          on: 'Atskaitymų sąrašas įjungtas. Trys sumos vėl juodraštyje.',
        },
        {
          key: 'tone',
          label: 'biuro rašymo maniera',
          count: 'tonas',
          name: 'biuro rašymo maniera',
          off: 'Biuro tonas išjungtas. Tie patys faktai, sausesnė kalba.',
          on: 'Biuro tonas įjungtas. Juodraštis vėl skamba biuro balsu.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Gerbiama p. Jankauskiene,' },
          off: { text: 'Gerbiamas nuomininke,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Ačiū, kad priminėte, ir atsiprašome, kad teko.' },
          off: { text: 'Pranešame, kad Jūsų užklausa gauta.' },
        },
        {
          key: 'rules',
          on: { text: 'Atsiskaitymą privalome pateikti per tris savaites nuo buto perdavimo' },
          tone: { text: 'Atsiskaitymas turi būti pateiktas per tris savaites nuo buto perdavimo' },
          off: { text: 'Atsiskaitymą pateiksime įprastais terminais' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'taigi jis pasieks Jus iki ', circle: '21 dienos', tail: '.' },
          tone: { text: 'taigi jis bus pateiktas iki 21 dienos.' },
          off: { text: 'tačiau tikslios datos negaliu nurodyti, kol nepatikrinsiu.' },
        },
        {
          key: 'deductions',
          on: { text: 'Iki šiol užfiksuoti du atskaitymai: valymas po išsikraustymo 850 EUR ir koridoriaus sienos pertepimas 400 EUR. Vadinasi, Jums grąžintina 4 750 EUR užstato dalis, ji bus pervesta į' },
          tone: { text: 'Iki šiol užregistruoti du atskaitymai: valymas po išsikraustymo 850 EUR ir koridoriaus sienos pertepimas 400 EUR. Grąžintina užstato dalis sudaro 4 750 EUR ir bus pervesta į' },
          off: { text: 'Gali būti tam tikrų atskaitymų. Sumas patvirtinsiu, kai patikrinsiu.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'mūsų turimą sąskaitą.' },
          tone: { text: 'registruose nurodytą sąskaitą.' },
          off: { text: 'Jūsų sąskaitą.' },
        },
      ],
    },
    {
      id: 'accounting',
      tab: 'Apskaita',
      deskName: 'Apskaitos',
      letter: {
        from: 'Mantas Adomaitis, UAB Staliaus dirbtuvės',
        subject: 'PVM deklaracija, ar vėluojame?',
        body: 'Mūsų buhalterė išėjo rugpjūtį, ir aš visiškai nežinau, kaip yra. Ar ketvirčio deklaracija pateikta ir ar esame skolingi? Verčiau išgirsiu tiesiai, negu gausiu raštą.',
      },
      sources: [
        {
          key: 'rules',
          label: 'pateikimo taisyklės',
          count: '1 eilutė',
          name: 'pateikimo taisyklės',
          off: 'Pateikimo taisyklės išjungtos. Juodraštis nebemini termino taisyklės.',
          on: 'Pateikimo taisyklės įjungtos. Vieno mėnesio ir septynių dienų taisyklė vėl juodraštyje.',
        },
        {
          key: 'deadline',
          label: 'ketvirčio terminas',
          count: '1 data',
          name: 'ketvirčio terminas',
          off: 'Terminas išjungtas. Data dingsta iš juodraščio.',
          on: 'Terminas įjungtas. 7 diena vėl juodraštyje.',
        },
        {
          key: 'file',
          label: 'to kliento byla',
          count: '2 eilutės',
          name: 'to kliento byla',
          off: 'Byla išjungta. Kliento vardas ir tiesioginis debetas dingsta iš juodraščio.',
          on: 'Byla įjungta. Kliento vardas ir tiesioginis debetas vėl juodraštyje.',
        },
        {
          key: 'deductions',
          label: 'jau apskaityti skaičiai',
          count: '3 sumos',
          name: 'jau apskaityti skaičiai',
          off: 'Apskaityti skaičiai išjungti. Trys sumos pašalintos iš juodraščio.',
          on: 'Apskaityti skaičiai įjungti. Trys sumos vėl juodraštyje.',
        },
        {
          key: 'tone',
          label: 'biuro rašymo maniera',
          count: 'tonas',
          name: 'biuro rašymo maniera',
          off: 'Biuro tonas išjungtas. Tie patys faktai, sausesnė kalba.',
          on: 'Biuro tonas įjungtas. Juodraštis vėl skamba biuro balsu.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Gerbiamas Mantai,' },
          off: { text: 'Gerbiamas kliente,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Ačiū, kad klausiate tiesiai, taip paprasčiau abiem.' },
          off: { text: 'Pranešame, kad Jūsų užklausa gauta.' },
        },
        {
          key: 'rules',
          on: { text: 'Ketvirčio iki liepos 31 d. deklaracija turi būti pateikta per vieną mėnesį ir septynias dienas po ketvirčio pabaigos' },
          tone: { text: 'Ketvirčio iki liepos 31 d. deklaracija teikiama per vieną mėnesį ir septynias dienas po ketvirčio pabaigos' },
          off: { text: 'Deklaracija bus pateikta įprastais terminais' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'taigi Jūsų pateikimo data yra ', circle: '7 diena', tail: '.' },
          tone: { text: 'taigi pateikimo data yra 7 diena.' },
          off: { text: 'tačiau tikslios datos negaliu nurodyti, kol nepatikrinsiu.' },
        },
        {
          key: 'deductions',
          on: { text: 'Viskas apskaityta iki liepos pabaigos: 41 280 EUR pardavimo PVM prieš 12 940 EUR atskaitos, taigi mokėtina 28 340 EUR iš' },
          tone: { text: 'Visi įrašai apskaityti iki liepos 31 d.: pardavimo PVM 41 280 EUR prieš 12 940 EUR atskaitos, mokėtina suma 28 340 EUR iš' },
          off: { text: 'Gali būti, kad reikės sumokėti. Sumą patvirtinsiu, kai patikrinsiu.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'mūsų turimos sąskaitos, tiesioginiu debetu.' },
          tone: { text: 'registruose nurodytos sąskaitos, tiesioginiu debetu.' },
          off: { text: 'Jūsų sąskaitos.' },
        },
      ],
    },
    {
      id: 'insurance',
      tab: 'Draudimas',
      deskName: 'Draudimo',
      letter: {
        from: 'Greta Paulauskienė, polisas 4471-C',
        subject: 'Vandens žala, vis dar jokio atsakymo',
        body: 'Virtuvės grindys išsipūtė 2 dieną, o Jūsų ekspertas atvyko po savaitės. Niekas man nepasakė, kas yra draudžiama. Ar išskaitą mokėsiu aš, ar Jūs, ir kada apskritai kas nors bus išmokėta?',
      },
      sources: [
        {
          key: 'rules',
          label: 'poliso formuluotė',
          count: '1 skyrius',
          name: 'poliso formuluotė',
          off: 'Poliso formuluotė išjungta. Juodraštis nebemini skyriaus ir išskaitos.',
          on: 'Poliso formuluotė įjungta. 4 skyrius ir išskaita vėl juodraštyje.',
        },
        {
          key: 'deadline',
          label: 'keturiolikos dienų standartas',
          count: '1 data',
          name: 'keturiolikos dienų standartas',
          off: 'Terminas išjungtas. Data dingsta iš juodraščio.',
          on: 'Terminas įjungtas. 18 diena vėl juodraštyje.',
        },
        {
          key: 'file',
          label: 'tos žalos byla',
          count: '2 eilutės',
          name: 'tos žalos byla',
          off: 'Byla išjungta. Draudėjos vardas ir sąskaita dingsta iš juodraščio.',
          on: 'Byla įjungta. Draudėjos vardas ir sąskaita vėl juodraštyje.',
        },
        {
          key: 'deductions',
          label: 'jau suderintos sumos',
          count: '3 sumos',
          name: 'jau suderintos sumos',
          off: 'Suderintos sumos išjungtos. Trys sumos pašalintos iš juodraščio.',
          on: 'Suderintos sumos įjungtos. Trys sumos vėl juodraštyje.',
        },
        {
          key: 'tone',
          label: 'biuro rašymo maniera',
          count: 'tonas',
          name: 'biuro rašymo maniera',
          off: 'Biuro tonas išjungtas. Tie patys faktai, sausesnė kalba.',
          on: 'Biuro tonas įjungtas. Juodraštis vėl skamba biuro balsu.',
        },
      ],
      salutation:
        {
          key: 'file',
          on: { text: 'Gerbiama p. Paulauskiene,' },
          off: { text: 'Gerbiamas draudėjau,' },
        },
      clauses: [
        {
          key: 'tone',
          on: { text: 'Ačiū, kad priminėte, ir atsiprašome, kad teko.' },
          off: { text: 'Pranešame, kad Jūsų užklausa gauta.' },
        },
        {
          key: 'rules',
          on: { text: 'Vandens nutekėjimas draudžiamas pagal Jūsų poliso 4 skyrių, išskaita 350 EUR' },
          tone: { text: 'Vandens nutekėjimas patenka į poliso 4 skyrių, išskaita 350 EUR' },
          off: { text: 'Vandens žala draudžiama įprasta tvarka' },
          sep: ', ',
        },
        {
          key: 'deadline',
          on: { text: 'o dėl draudimo apimties atsakome per keturiolika dienų nuo eksperto išvados, tai yra iki ', circle: '18 dienos', tail: '.' },
          tone: { text: 'o draudimo apimtis patvirtinama per keturiolika dienų nuo eksperto išvados, tai yra iki 18 dienos.' },
          off: { text: 'tačiau tikslios datos negaliu nurodyti, kol nepatikrinsiu.' },
        },
        {
          key: 'deductions',
          on: { text: 'Ekspertas patvirtino 6 200 EUR už grindis ir 1 150 EUR už džiovinimą, taigi atskaičius išskaitą 7 000 EUR keliauja į' },
          tone: { text: 'Ekspertas patvirtino 6 200 EUR už grindis ir 1 150 EUR už džiovinimą; atskaičius išskaitą mokėtina 7 000 EUR į' },
          off: { text: 'Gali būti, kad bus išmokėta. Sumas patvirtinsiu, kai patikrinsiu.' },
        },
        {
          key: 'file',
          dep: 'deductions',
          on: { text: 'mūsų turimą sąskaitą.' },
          tone: { text: 'registruose nurodytą sąskaitą.' },
          off: { text: 'Jūsų sąskaitą.' },
        },
      ],
    },
  ],
};
