import type { Content } from '../types';

export const form: Content['form'] = {
  eyebrow: 'Ką man daryti dabar',
  title: 'Trys klausimai. Mažiau nei minutė.',
  lead: 'Taip išsiaiškiname, ar pokalbis vertas Jūsų laiko. Jei ne, šis puslapis taip ir pasakys, užuot Jus užregistravęs.',
  formNo: 'Tinkamumo patikra',
  optional: 'Neprivaloma',
  companyLabel: 'Įmonės pavadinimas',
  companyPlaceholder: 'Pavadinimas, nurodomas Jūsų sąskaitose',
  emailLabel: 'Darbo el. paštas',
  emailPlaceholder: 'jus@jusuimone.lt',
  emailHint: 'Naudojame tik pokalbio detalėms ir bandomojo laikotarpio sutarčiai išsiųsti.',
  phoneLabel: 'Telefonas',
  phoneHint: 'Kad galėtume susisiekti, jei laiškas nepasieks. Naudosime tik šiam pokalbiui.',
  emailFreeWarning:
    'Atrodo, kad tai asmeninis adresas. Jis tiks, bet darbo adresas padeda mums rasti Jūsų įmonę prieš pokalbį.',
  teamSizeLabel: 'Kiek žmonių kasdien tvarko laiškus?',
  teamSizeOptions: [
    { value: '1-9', label: 'nuo 1 iki 9 žmonių' },
    { value: '10-24', label: 'nuo 10 iki 24 žmonių' },
    { value: '25-49', label: 'nuo 25 iki 49 žmonių' },
    { value: '50+', label: '50 ar daugiau' },
  ],
  emailClientLabel: 'Kuo naudojasi komanda?',
  emailClientOptions: [
    { value: 'outlook', label: 'Outlook' },
    { value: 'gmail', label: 'Gmail' },
    { value: 'other', label: 'Kažkuo kitu' },
  ],
  roleLabel: 'Jūsų pareigos',
  roleOptions: [
    { value: 'owner_partner', label: 'Savininkas arba partneris' },
    { value: 'ops_office_manager', label: 'Veiklos arba biuro vadovas' },
    { value: 'it_admin', label: 'IT arba administracija' },
    { value: 'other', label: 'Kita' },
  ],
  otherLabel: 'Parašykite, kurį',
  choosePrompt: 'Pasirinkite',
  steps: ['Apie komandą', 'Kaip su Jumis susisiekti'],
  stepsLabel: 'Patikrinimas dviem žingsniais',
  continueCta: 'Toliau',
  backCta: 'Atgal',
  submit: 'Patikrinkite, ar tinkame',
  submitting: 'Palaukite akimirką',
  required: 'Šį lauką reikia užpildyti.',
  invalidEmail: 'Šis adresas atrodo neužbaigtas.',
  invalidPhone: 'Atrodo, kad skaitmenų numeriui per mažai.',
  privacyNote: 'Naudojama pasiruošti pokalbiui. Jokių sąrašų, jokio perpardavimo.',
};
